# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "10c388bc0035d29efa579e8af3b99286"
name = "efficient-policy-app"
handle = "efficient-policy-app-10"
application_url = "https://bosnia-comparable-earlier-publisher.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://bosnia-comparable-earlier-publisher.trycloudflare.com/auth/callback",
  "https://bosnia-comparable-earlier-publisher.trycloudflare.com/auth/shopify/callback",
  "https://bosnia-comparable-earlier-publisher.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
